### ISSUE TITLE
Error module 'mistune' has no attribute 'BlockGrammar' maybe linked to #6531 (?)

### ISSUE THREAD

**Issue by g-vidal** [deathbeds/jupyterlab-fonts#56]
After installation of jupyterlab-fonts and running `jupyter lab` inside my virtual env (see config below) I get twice the following error message :
```shell
[E 2022-09-30 09:53:33.813 ServerApp] Uncaught exception GET /api/nbconvert?1664524413629 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1664524413629', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/vidal/.local/share/virtualenvs/FlaskVenv-XZ2RGVQf/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/home/vidal/.local/share/virtualenvs/FlaskVenv-XZ2RGVQf/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 29, in get
        from nbconvert.exporters import base
      File "/home/vidal/.local/share/virtualenvs/FlaskVenv-XZ2RGVQf/lib/python3.10/site-packages/nbconvert/__init__.py", line 3, in <module>
        from . import filters, postprocessors, preprocessors, writers
      File "/home/vidal/.local/share/virtualenvs/FlaskVenv-XZ2RGVQf/lib/python3.10/site-packages/nbconvert/filters/__init__.py", line 8, in <module>
        from .markdown import *
      File "/home/vidal/.local/share/virtualenvs/FlaskVenv-XZ2RGVQf/lib/python3.10/site-packages/nbconvert/filters/markdown.py", line 13, in <module>
        from .markdown_mistune import markdown2html_mistune
      File "/home/vidal/.local/share/virtualenvs/FlaskVenv-XZ2RGVQf/lib/python3.10/site-packages/nbconvert/filters/markdown_mistune.py", line 37, in <module>
        class MathBlockGrammar(mistune.BlockGrammar):
    AttributeError: module 'mistune' has no attribute 'BlockGrammar'
[W 2022-09-30 09:53:33.814 ServerApp] wrote error: 'Unhandled error'
[E 2022-09-30 09:53:33.814 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0"
    }
[E 2022-09-30 09:53:33.814 ServerApp] 500 GET /api/nbconvert?1664524413629 (127.0.0.1) 31.35ms referer=http://localhost:8888/lab
```
When I uninstall jupyterlab-fonts the eror does not disappear and I have to reinstall nbconvert to get back a vlean jupyter lab
Configuration :
Linux ####### 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux
pipenv, version 2022.9.24
Pipfle :
```shell
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
jupyter = "*"
jupyterlab = "*"
jupyter-nbextensions-configurator = "*"
voila = "*"
jupyterlab-hdf = "*"
flask = "*"
jinja2 = "*"
gunicorn = "*"
psycopg2 = "*"
flask-sqlalchemy = "*"
ipywidgets = "*"
flexx = "*"
plotly = "*"
numpy = "*"
pandas = "*"
six = "*"
wheel = "*"
pandoc = "*"
pandocfilters = "*"
pypandoc = "*"
sqlalchemy = "*"
pymysql = "*"
jupyterlab-language-pack-fr-fr = "*"
psycopg2-binary = "*"
flask-migrate = "*"
requests = "*"
spidev = "*"
pillow = "*"
setuptools = "*"
kaleido = "*"
nbconvert = "*"**
jupyterlab-fonts = "*"
mistune = "*"
pipenv = "*"

[dev-packages]

[requires]
python_version = "3.10"
```

**Comment by bollwyvl** [comment]
`jupyterlab-fonts` only depends on `jupyterlab =3.*`.

I don't really know much about `Pipfiles`, and all the `*` don't really tell me much.

Recently, a few larger dependencies of jupyterlab made some bigger, security-related changes, so you may need to ensure you have:

```
nbconvert >=7
mistune >=2
```

**Comment by g-vidal** [comment]
The issue came from dependency conflicts between  sytem python / user python / pipenv virtual env python. 
To clean up the situation I removed all modules installed locally by the user then removed the `~/.jupyter folder`

Everything is OK now, jupyterlab-fonts is fully operational.
